#!/usr/bin/env python3
"""Builds supabase/nevorai-os/academy_0001_schema.sql from a pg_dump of the LIVE Academy OS `public` schema.

Academy OS moves from its own Supabase project (tables in `public`) into the shared
Nevorai OS project, schema `academy`. Input: `pg_dump --schema-only --schema=public --no-owner`
(WITH privileges) of the old project. Rules applied:
  - public.<x> -> academy.<x>; function `SET search_path TO 'public'` -> 'academy'
    (string literals like visibility = 'public' are left alone: only `public.` and the search_path form change)
  - schema creation, default privileges and the event-trigger function rls_auto_enable() are dropped
    (shared database: no database-wide event triggers; platform.create_app_schema() sets defaults)
  - table grants are cut to what the API can use (SELECT/INSERT/UPDATE/DELETE); TRUNCATE/REFERENCES/TRIGGER/MAINTAIN go.
    Column-level grants, function EXECUTE grants/revokes and sequence grants are kept exactly as they were.
  - storage bucket tenant-assets -> academy-assets (private) with its 9 policies, names schema-qualified
  - realtime publication gets the same 9 tables
Run:  python3 scripts/build-academy-nevorai-os-sql.py [dump.sql] [out.sql]
      (defaults: ~/academy-move-private/schema_with_grants.sql -> supabase/nevorai-os/academy_0001_schema.sql;
       `academy-move.sh dump` builds a second copy from the fresh dump and compares it: any difference = the live structure changed)
"""
import os, re, sys

src = os.path.expanduser(sys.argv[1] if len(sys.argv) > 1 else '~/academy-move-private/schema_with_grants.sql')
dst = os.path.expanduser(sys.argv[2]) if len(sys.argv) > 2 else 'supabase/nevorai-os/academy_0001_schema.sql'
text = open(src).read()
text = re.sub(r'^\\(un)?restrict .*\n', '', text, flags=re.M)  # pg_dump 17.11 guard lines

# 1. drop the event-trigger function and everything that mentions it
text, n = re.subn(r'--\n-- Name: rls_auto_enable\(\).*?\$\$;\n', '', text, flags=re.S)
assert n == 1, 'rls_auto_enable block not found'
text = re.sub(r'^(GRANT|REVOKE) [^\n]*public\.rls_auto_enable\(\)[^\n]*\n', '', text, flags=re.M)
text = re.sub(r'--\n-- Name: FUNCTION rls_auto_enable\(\); Type: ACL[^\n]*\n--\n\n?', '', text)
assert 'rls_auto_enable' not in text, [l for l in text.split('\n') if 'rls_auto_enable' in l][:3]

# 2. statement-level removals / rewrites (every one of these is a single line in pg_dump output)
out = []
for line in text.split('\n'):
    if line.startswith(('CREATE SCHEMA public', 'COMMENT ON SCHEMA public', 'GRANT USAGE ON SCHEMA public', 'ALTER DEFAULT PRIVILEGES')):
        assert line.rstrip().endswith(';'), line
        continue
    m = re.match(r'^GRANT ALL ON TABLE (public\.\S+) TO (anon|authenticated|service_role);$', line)
    if m:
        priv = 'ALL' if m.group(2) == 'service_role' else 'SELECT, INSERT, UPDATE, DELETE'
        out.append(f'GRANT {priv} ON TABLE {m.group(1)} TO {m.group(2)};')
        continue
    m = re.match(r'^GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE (public\.\S+) TO anon;$', line)
    if m:  # the tenants table: anon may write (RLS decides) but has no blanket SELECT
        out.append(f'GRANT INSERT, UPDATE, DELETE ON TABLE {m.group(1)} TO anon;')
        continue
    out.append(line)
sql = '\n'.join(out)

# 3. schema rename
sql = sql.replace("search_path TO 'public'", "search_path TO 'academy'")
sql = re.sub(r'\bpublic\.', 'academy.', sql)
# 3b. admin_set_student_password is SECURITY DEFINER with NO search_path and calls crypt()/gen_salt() unqualified
# (they resolved through the role path in the old project). Pin the path and qualify them: a hardening, same behaviour.
old_hdr = "CREATE FUNCTION academy.admin_set_student_password(_tenant_id uuid, _student_id uuid, _new_password text) RETURNS void\n    LANGUAGE plpgsql SECURITY DEFINER\n    AS $$"
assert old_hdr in sql, 'admin_set_student_password header not found'
sql = sql.replace(old_hdr, old_hdr.replace("SECURITY DEFINER\n", "SECURITY DEFINER\n    SET search_path TO 'academy', 'extensions'\n"))
assert "crypt(_new_password, gen_salt('bf'))" in sql
sql = sql.replace("crypt(_new_password, gen_salt('bf'))", "extensions.crypt(_new_password, extensions.gen_salt('bf'))")

assert not re.search(r"\bpublic\.", sql), 'public. left'
assert "search_path TO 'public'" not in sql
# every remaining 'public' literal must be a visibility value or the jsonb key at "'public', to_jsonb(pm)"
odd = [l for l in sql.split('\n') if "'public'" in l and "'public'::text" not in l and "'public', to_jsonb(pm)" not in l]
assert not odd, odd[:5]

head = """-- Academy OS inside Nevorai OS, schema `academy`. GENERATED by scripts/build-academy-nevorai-os-sql.py
-- from a pg_dump of the live old project. Do not edit by hand; re-run the script.
-- Run AFTER:  select platform.create_app_schema('academy', 'Academy OS');   (+ add `academy` to Exposed schemas)
-- Run with:   psql "$NEW_DB_URL" -X -v ON_ERROR_STOP=1 --single-transaction -f academy_0001_schema.sql
"""

tables = re.findall(r'^CREATE TABLE academy\.(\w+)', sql, flags=re.M)
assert len(tables) == 104, len(tables)

realtime = ['attendance_sessions', 'attendance_marks', 'mc_matches', 'mc_innings', 'mc_ball_events',
            'notifications', 'automation_events', 'automation_executions', 'automation_deliveries']
for t in realtime:
    assert t in tables, t

# Views are read-only for the API roles. In the shared project the schema's DEFAULT privileges would otherwise hand
# `authenticated` INSERT/UPDATE/DELETE on every view; tenants_public_directory (security_invoker=off, auto-updatable) would
# then let any logged-in user rename or DELETE an academy, bypassing RLS. The old project gave it SELECT only, and the app
# only ever reads from all 6 views, so every view ends up SELECT-only for anon and authenticated.
views = re.findall(r'^CREATE VIEW academy\.(\w+)', sql, flags=re.M)
assert len(views) == 6, views
view_fix = "\n-- ════ views: read-only for anon/authenticated (see build script) ════\n" + "".join(
    f"REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE academy.{v} FROM anon, authenticated;\n" for v in views)

tail = view_fix + """
-- ════ storage: bucket academy-assets (private) + the 9 policies of the old tenant-assets bucket ════
-- Policy bodies were read from the live project; helper functions and `students` are schema-qualified
-- because storage policies do not run with academy on their search_path.
-- NOTE (existing behaviour, kept): the two "student photo" policies compare foldername(s.name) where s is the
-- STUDENT row (its name), not the uploaded object's name, so they almost never match. Fix separately.
insert into storage.buckets (id, name, public) values ('academy-assets', 'academy-assets', false) on conflict (id) do nothing;

create policy "academy-assets anon read public sections" on storage.objects as permissive for select to anon
  using (bucket_id = 'academy-assets'
    and (storage.foldername(name))[2] = any (array['public','gallery','hero','logo_url','founder','cta','star_players','upi_qr_url','players'])
    and academy.is_active_tenant(((storage.foldername(name))[1])::uuid));
create policy "academy-assets anon registration upload" on storage.objects as permissive for insert to anon
  with check (bucket_id = 'academy-assets' and (storage.foldername(name))[2] = 'registration'
    and academy.is_active_tenant(((storage.foldername(name))[1])::uuid));
create policy "academy-assets authenticated registration upload" on storage.objects as permissive for insert to authenticated
  with check (bucket_id = 'academy-assets' and (storage.foldername(name))[2] = 'registration'
    and academy.is_active_tenant(((storage.foldername(name))[1])::uuid));
create policy "academy-assets member delete" on storage.objects as permissive for delete to authenticated
  using (bucket_id = 'academy-assets' and (academy.is_platform_admin(auth.uid()) or academy.is_tenant_member(auth.uid(), ((storage.foldername(name))[1])::uuid)));
create policy "academy-assets member insert" on storage.objects as permissive for insert to authenticated
  with check (bucket_id = 'academy-assets' and (academy.is_platform_admin(auth.uid()) or academy.is_tenant_member(auth.uid(), ((storage.foldername(name))[1])::uuid)));
create policy "academy-assets member read all" on storage.objects as permissive for select to authenticated
  using (bucket_id = 'academy-assets' and (academy.is_platform_admin(auth.uid()) or academy.is_tenant_member(auth.uid(), ((storage.foldername(name))[1])::uuid)));
create policy "academy-assets member update" on storage.objects as permissive for update to authenticated
  using (bucket_id = 'academy-assets' and (academy.is_platform_admin(auth.uid()) or academy.is_tenant_member(auth.uid(), ((storage.foldername(name))[1])::uuid)))
  with check (bucket_id = 'academy-assets' and (academy.is_platform_admin(auth.uid()) or academy.is_tenant_member(auth.uid(), ((storage.foldername(name))[1])::uuid)));
create policy "academy-assets student photo insert" on storage.objects as permissive for insert to authenticated
  with check (bucket_id = 'academy-assets' and (storage.foldername(name))[2] = any (array['players','registration'])
    and exists (select 1 from academy.students s where s.user_id = auth.uid() and s.tenant_id = ((storage.foldername(s.name))[1])::uuid));
create policy "academy-assets student photo update" on storage.objects as permissive for update to authenticated
  using (bucket_id = 'academy-assets' and (storage.foldername(name))[2] = any (array['players','registration'])
    and exists (select 1 from academy.students s where s.user_id = auth.uid() and s.tenant_id = ((storage.foldername(s.name))[1])::uuid))
  with check (bucket_id = 'academy-assets' and (storage.foldername(name))[2] = any (array['players','registration'])
    and exists (select 1 from academy.students s where s.user_id = auth.uid() and s.tenant_id = ((storage.foldername(s.name))[1])::uuid));

-- ════ realtime: same 9 tables as the old project ════
alter publication supabase_realtime add table """ + ', '.join('academy.' + t for t in realtime) + """;

insert into platform.app_migrations (app_key, version) values ('academy', 'academy_0001_schema') on conflict do nothing;
"""
os.makedirs(os.path.dirname(dst) or '.', exist_ok=True)
open(dst, 'w').write(head + sql + tail)
print('ok', len(sql), 'bytes of schema;', len(tables), 'tables')
